### ISSUE TITLE
Placing items in my bike glovebox then getting off and on they disappear[BUG]

### ISSUE THREAD

**Issue by cdotdatruth** [ElusionPDX/Ze3o-Reports#100]
**Describe the bug**
The title says it all. I placed wine bottles and burgers in my bike glovebox which can hold 40 KG. Then I get off the bike and get back on and the bottles and burgers are gone. I have lost 39 bottles and 6 burgers so far.
**To Reproduce**
1. Go to duke sit on it open glovebox with K place any item in it. Get off bike, then sit back on it and hit K again and items will be gone.

**Expected behavior**
Place items in glovebox and they stay there until I take them out.

**Screenshots**
https://i.imgur.com/SuDJ7Ki.jpg
https://i.imgur.com/IakytBT.jpg
https://i.imgur.com/lVxVPqb.jpg
**Desktop (please complete the following information):**
 - OS: Windows
 - GPU: 2080 Super
 - CPU: i7 10700k

**Additional context**

**Comment by ElusionPDX** [comment]
Try it now.
