### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JosephPentz** [ElusionPDX/Ze3o-Reports#103]
**Describe the bug**
Cannot add a vest for police because weight too heavy but it isn't.

**To Reproduce**
1. Have inventory at 16/21KG
2. Attempt to add 1 vest which is 5KG/5000G

**Expected behavior**
Item should add at 16+5=21

**Screenshots**
https://i.imgur.com/vTDqITo.jpg

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] WIN 10
 - GPU: [e.g. gtx1060] RTX 3080
 - CPU: [e.g. FX8350] I9 990K

**Comment by ElusionPDX** [comment]
you have more then 16kg. prob like 16.80kg   see all the .## on some of the items
![image](https://user-images.githubusercontent.com/19332765/120527636-8f3d1880-c3a8-11eb-8cec-4b298d967af0.png)
