### ISSUE TITLE
[BUG] Lockpicking time bypass for vehicles

### ISSUE THREAD

**Issue by CPatelCLT** [ElusionPDX/Ze3o-Reports#108]
**Describe the bug**
You are able to bypass the time it takes to lockpick a vehicle entirely by starting a search of the vehicle then using the lockpick. The vehicle starts up and is mobile well before either action is finished

**To Reproduce**
1) Break into vehicle
2) Start a search using the G key
3) Start lockpicking by "using" a lockpick or pressing the key for whatever slot the lockpick is in
4) Observe that you are able to drive before the lockpicking action is complete

**Expected behavior**
Not able to perform two actions at the same time, and lockpicking a vehicle should take the full time that it's meant to take

**Screenshots**
https://www.youtube.com/watch?v=k96yUOoCCT0

**Comment by Xodius** [comment]
Tested this - Not an issue anymore.
