### ISSUE TITLE
[BUG] Health Regenerating

### ISSUE THREAD

**Issue by zhrocks11** [ElusionPDX/Ze3o-Reports#11]
**Describe the bug**

Health is regenerating with injuries - All injuries are regen-ing, We tested melee with weapon, mele without weapon, damage from vehicle, and gun damage, after taking injuries below 50% you will regen health.  

**To Reproduce**

Get Injured, from any method of damage - testing methods used above - and you will start to regen health after about 20 seconds from taking last damage 

**Expected behavior**

Expected behavior would be to take damage and not have health regen 

**Screenshots**

Contact myself if video is needed

**Desktop (please complete the following information):**
 

NOT APPLICABLE

**Additional context**

Any other context needed please contact myself

**Comment by ElusionPDX** [comment]
https://github.com/ElusionPDX/ZeroLive/commit/169531da7e3f3558fb948a189d16239005c30184
