### ISSUE TITLE
[BUG] [Banking] Daily limit isn't truly being enforced at ATM's

### ISSUE THREAD

**Issue by Xodius** [ElusionPDX/Ze3o-Reports#12]
**Describe the bug**
The daily limit on ATM's can be skirted with taking out lesser amounts of cash from ATM's

**To Reproduce**
1. Go to ATM
2. Take out 1000 dollars at a time until you get prompted that you are over the limit
3. Set a number to 999 and take out cash
4.  Keep dropping that number in increments of 1 dollar and see that you are still taking out cash.

**Expected behavior**
If there is a true limit on ATM withdrawals then you shouldn't be able to take out cash

**Screenshots**
![image](https://user-images.githubusercontent.com/6254089/118067834-3274b200-b356-11eb-898a-e62168214fa2.png)

**Additional context**
See from post below in discord:
https://discord.com/channels/744304784303194184/744304787046269019/842220528872980516

**Comment by ElusionPDX** [comment]
https://github.com/ElusionPDX/ZeroLive/commit/844e752fe3d1ecaf5034136f7f99d00c77e1acbd
