### ISSUE TITLE
[ENHANCEMENT] [Pillbox Hospital] E- Checkin can be done from too far away

### ISSUE THREAD

**Issue by Xodius** [ElusionPDX/Ze3o-Reports#13]
**Describe the bug**
Check in at pillbox front desk can be activated from a long distance

**To Reproduce**
1. Go to pillbox hospital and observe how far away it can be activated

**Expected behavior**
Activation for the hospital should be right up against the desk to avoid accidental activation

**Screenshots**
![image](https://user-images.githubusercontent.com/6254089/118069140-7799e380-b358-11eb-8579-0831586fa8a4.png)

**Comment by ElusionPDX** [comment]
https://github.com/ElusionPDX/ZeroLive/commit/f248948409aebf2b59bb11539da59f0cc811ed4c
