### ISSUE TITLE
[BUG] [ADMIN] Create:Doors doesn't show authorized jobs

### ISSUE THREAD

**Issue by Xodius** [ElusionPDX/Ze3o-Reports#14]
**Describe the bug**
Create:Doors doesn't show authorized jobs

**To Reproduce**
1. Perform a Create:Doors
2. Get to "Authorized Jobs" prompt"
3. Notice there are no jobs listed

**Expected behavior**
Should be able to create doors with associated whitelisted jobs

**Screenshots**
![image](https://user-images.githubusercontent.com/6254089/118069692-761ceb00-b359-11eb-807d-c2d0c56ca1a7.png)

**Comment by ElusionPDX** [comment]
https://github.com/ElusionPDX/ZeroLive/commit/ca45d0b499446717e1e492bb966b64508c4a3971
