### ISSUE TITLE
[BUG] Wine Selling van spawner doesn't give keys to the spawned van.

### ISSUE THREAD

**Issue by robo50111** [ElusionPDX/Ze3o-Reports#15]
**Describe the bug**
Spawning the Wine Selling van at the Vineyard doesnt give keys to the van. Lockpicking or hotwireing are the only two options to start the car

**To Reproduce**
1. Get grapes and make wine
2. Go to the front door of the big wine house to "sell the wine" That spawns the vehicle. 
3. The van spawns, get in the van. When you get in, you dont have keys to that van and you have to lockpick or hotwire it.

**Expected behavior**
When you spawn the vehicle, it should give you the keys to that van.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Win 10
 - GPU: GTX1070
 - CPU: I7-8700k

**Additional context**
N/A

**Comment by ElusionPDX** [comment]
https://github.com/ElusionPDX/ZeroLive/commit/3d634b29fbd25d67429eabe3a665758685c8fe7c
