### ISSUE TITLE
Crash report: unrelated? Repeated Game Crashing near intersection @ Pillbox/Bus Station

### ISSUE THREAD

**Issue by TLCKAT** [ElusionPDX/Ze3o-Reports#17]
Multiple times, when passing Pillbox/bus station from downtown (heading northbound onto highway), my game crashed. This has happened multiple times. here's the report and snippet of the report as well. Unsure if it's server related or a FiveM issue, so here ya go incase it's something server side. 

Recreation:
Head northbound past Pillbox Hospital/Bus Station heading toward Harmony. 
Could be speed related? I'm usually going at least 50 when I pass. I'm my next login, I'll see if it's just in general or not.

![image](https://user-images.githubusercontent.com/84049876/118190288-e6d30e80-b410-11eb-9a19-c81fe021303c.png)

[   6637125] [    DumpServer]                 1468/ Process crash captured. Crash dialog content:
[   6637125] [    DumpServer]                 1468/ GTA5.exe!sub_1415F40D4 (0x4b)
[   6637125] [    DumpServer]                 1468/ An error at GTA5.exe!sub_1415F40D4 (0x4b) caused FiveM to stop working. A crash report is being uploaded to the FiveM developers.
[   6637125] [    DumpServer]                 1468/ 
[   6637125] [    DumpServer]                 1468/ Legacy crash hash: nine-paris-eighteen
[   6637125] [    DumpServer]                 1468/ Stack trace:
[   6637125] [    DumpServer]                 1468/   GTA5.exe!sub_1415F40D4 (0x4b)
[   6637125] [    DumpServer]                 1468/   GTA5.exe!sub_1405EFF9C (0x38)
[   6637125] [    DumpServer]                 1468/   GTA5.exe!sub_1408D2F10 (0x3f)
[   6637125] [    DumpServer]                 1468/   GTA5.exe!sub_1408F6D48 (0xa0)
[   6637125] [    DumpServer]                 1468/   GTA5.exe!sub_1408FE83C (0x46)
[   6637125] [    DumpServer]                 1468/   GTA5.exe!sub_14055209C (0x50)
[   6637125] [    DumpServer]                 1468/   GTA5.exe!sub_1404F88B0 (0x28)
[   6637125] [    DumpServer]                 1468/ 
[   6644937] [    DumpServer]                 1468/ Crash report service returned si-ecac36fff6444ddeb05277801c60ec91

**Comment by TLCKAT** [comment]
Update, it's not the speed. blew through at multiple speeds, and did some loops, circling near pawn shop rolling by and coming back downtown over near the job center. Can't recreate it. Unsure what's causing it.

**Comment by Xodius** [comment]
I've had this a couple of times now around that same area. I heard of a couple others reporting is as well. See attached screenshot and crashdump.

![image](https://user-images.githubusercontent.com/6254089/118195997-1b3ece80-b401-11eb-8fb0-22238f4bcd12.png)

[CfxCrashDump_2021_05_13_22_37_30.zip](https://github.com/ElusionPDX/Ze3o-Reports/files/6475414/CfxCrashDump_2021_05_13_22_37_30.zip)

**Comment by ElusionPDX** [comment]
Bus mlo was pulled, hope this sloves it as its the only new thing over there
