### ISSUE TITLE
[BUG] [Admin] Door lock in Pillbox can't be removed using "doors:remove"

### ISSUE THREAD

**Issue by Xodius** [ElusionPDX/Ze3o-Reports#18]
**Describe the bug**
Door lock in Pillbox Hospital can't be removed using "doors:remove"

**To Reproduce**
1. Go to door at coord in screenshot
2. type "doors:remove" in text console
3. Note door lock won't go away

**Expected behavior**
Door lock should be removed upon execution of doors:remove

**Screenshots**
![image](https://user-images.githubusercontent.com/6254089/118193526-b2edee00-b3fc-11eb-89b9-ddb0e6bead74.png)

**Additional context**

**Comment by ElusionPDX** [comment]
removed
