### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TLCKAT** [ElusionPDX/Ze3o-Reports#2]
**Describe the bug**
Unknown if the "green" on the catch bar for fishing (when your supposed to hit E) is supposed to be stationary at the top of the bar, or randomly placed at different spots on the bar.

**To Reproduce**
1. Hit T
2. type /fish
3. hit G when prompted to cast
4. when prompted , hit E when the meter is within the green on the bar.

**Expected behavior**
I'm submitting this incase the "green" is supposed to be in different places with each cast. I've done 15+ casts and the green is always at the top of the bar.  Kind of makes it too easy.

**Screenshots**

![image](https://user-images.githubusercontent.com/84049876/117896840-76e94a80-b28f-11eb-897c-610d6498b9a0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 64
 - GPU: 8192MB ATI Radeon RX 580 Series 
 - CPU: AMD Ryzen 7 3700X

**Additional context**
Just in case it was supposed to be in different places. if not, ignore this report

**Comment by ElusionPDX** [comment]
It stays in the same spot. Is uses a GUI draw from a DLC in gta5 for tennis power swing. Its not something that can be changed. Maybe down the road edit it to a different GUI
