### ISSUE TITLE
[BUG] Police Vehicles

### ISSUE THREAD

**Issue by ChiefDeputyFlowers** [ElusionPDX/Ze3o-Reports#28]
**Describe the bug**
The Q key does not produce the siren, E takes away the ability to use the airhorn.

**Comment by ChiefDeputyFlowers** [comment]
Also E is the lights right now...

**Comment by ElusionPDX** [comment]
its due to lux_vehcontrol is not running at this time. Added it to the startup and started it now. have fun mister weewooo
