### ISSUE TITLE
Unknown Artifact/visual/item off the cost of zipcode 612

### ISSUE THREAD

**Issue by TLCKAT** [ElusionPDX/Ze3o-Reports#3]
**Describe the bug**
Upon leaving the docks from checking fishing, i noticed off the coast of the docks at 612 zipcode, I saw a green bar across the ocean off in the distance, with a red outline.  I relogged and brought all my graphic settings down to low, to see if it was just my system. Still there

**To Reproduce**
1. Go to zipcode 612 
2. stand at end of the docks 
3. look to the Southeast

**Expected behavior**
N/A

**Screenshots**

![image](https://user-images.githubusercontent.com/84049876/117897715-5b7f3f00-b291-11eb-841a-c06cf2c714eb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 64
 - GPU: 8192MB ATI Radeon RX 580 Series 
 - CPU: AMD Ryzen 7 3700X

**Additional context**

**Comment by ElusionPDX** [comment]
This is a place holder Draw box for a WIP system.
