### ISSUE TITLE
[BUG] Respawn after timer is up places you in the MRPD front desk

### ISSUE THREAD

**Issue by Xodius** [ElusionPDX/Ze3o-Reports#36]
**Describe the bug**
Respawn after timer is up places you in the MRPD front desk

**To Reproduce**
1. Kill yourself and wait for timer to be finished.
2. Press H to respawn
3. Note you respawn at MRPD front office

**Expected behavior**
Expected to respawn at a hospital (Pillbox?)

**Comment by ElusionPDX** [comment]
On duty police respawn at mrpd when timer is up and you press H
