### ISSUE TITLE
[BUG] UPS Job-- delivery location: DMV

### ISSUE THREAD

**Issue by TLCKAT** [ElusionPDX/Ze3o-Reports#38]
**Describe the bug**
After delivering my first package, I was given another location "The DMV", and the GPS "marked the location" for me, but it was NOT the DMV, but the Maze Arena. After carrying package around the arena and didn't find a drop off location there, I proceeded to the DMV and checked for a drop off location there. There isn't one at either place. checked inside and outside and around back of both buildings, no [E] option to "drop off"

**To Reproduce**
1. Start UPS Job
2. Get "DMV" delivery task
3. Look at marked location for DMV on map, and/or go there and to the DMV. 

**Expected behavior**
expected to have GPS mark the DMV location, and have a "[E]" option at the DMV somewhere to drop package off.

**Screenshots**
![image](https://user-images.githubusercontent.com/84049876/118303434-74673a80-b4b3-11eb-9c2c-bd5658d7e24f.png)

**Desktop (please complete the following information):**
  - OS: Windows 10 Home 64
 - GPU: 8192MB ATI Radeon RX 580 Series 
 - CPU: AMD Ryzen 7 3700X

**Additional context**

**Comment by TLCKAT** [comment]
Update, found the "DMV" drop off location.  The old DMV location:

![image](https://user-images.githubusercontent.com/84049876/118304752-13d8fd00-b4b5-11eb-84cc-252fbb24cc89.png)

**Comment by Xodius** [comment]
This job was removed.
