### ISSUE TITLE
Blimps for Police are broken

### ISSUE THREAD

**Issue by LocoGuero** [ElusionPDX/Ze3o-Reports#39]
Not only can they not be seen far away. They also are not accurate. See the attached photo. On the map you can see me, my car, Jackson, and her car. Her blimp is a block away. 
![Capture](https://user-images.githubusercontent.com/84199174/118307419-303b6080-b4da-11eb-9e71-b68a1e892009.PNG)

**Comment by ElusionPDX** [comment]
fixed in https://github.com/ElusionPDX/ZeroLive/commit/95f8e01fee56c60d69eb2747317668aedbbb0a89
