### ISSUE TITLE
Apartment Storage -- /outfits command at Country Lane (zip code 559) isn't working.

### ISSUE THREAD

**Issue by TLCKAT** [ElusionPDX/Ze3o-Reports#4]
**Describe the bug**
closet in the apartment shows a "/outfits" when facing my closet. when i do T, /outfits, I get an error saying "No Such Command"
**To Reproduce**
Stand in your apartment at Country Lane, and hit T

1. Stand in your apartment at Country Lane
2. Hit T
3. type /outfits

**Expected behavior**
Unsure if /outfits is supposed to work, or if it's supposed to say [E] Outfits.  /outfits command produces an error.

**Screenshots**
![image](https://user-images.githubusercontent.com/84049876/117900109-8ddf6b00-b296-11eb-9eb9-08357f44fb34.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 64
 - GPU: 8192MB ATI Radeon RX 580 Series 
 - CPU: AMD Ryzen 7 3700X

**Additional context**

**Comment by Xodius** [comment]
I am not seeing the commands for this showing up in the / list. Different system or not turned on?

**Comment by ElusionPDX** [comment]
Fixed in comment https://github.com/ElusionPDX/ZeroLive/commit/848811654ae40074228ad2772e2e937d44825db4
