### ISSUE TITLE
[BUG] Paleto Bar Postal 3011

### ISSUE THREAD

**Issue by ChiefDeputyFlowers** [ElusionPDX/Ze3o-Reports#40]
**Describe the bug**
You fall through the earth at the bar in Paleto.

**Screenshots**
https://i.imgur.com/76CPmAo.jpg
https://i.imgur.com/KIxjZ2E.jpg
https://i.imgur.com/tVNNhYF.png

**Comment by ElusionPDX** [comment]
fixed in https://github.com/ElusionPDX/ZeroLive/commit/06f86af0e6f02ed9031b8cb97cf2b589300b468b
