### ISSUE TITLE
[BUG] Character Creation - Stays ped unless cycle Gender

### ISSUE THREAD

**Issue by JosephPentz** [ElusionPDX/Ze3o-Reports#42]
You stay as default PED in character creation screen unless you cycle your gender first.

**Comment by ElusionPDX** [comment]
Yes??  im lost on what the issues is?

**Comment by JosephPentz** [comment]
When you go into character creation, it defaults to male. If you want male, you will not change this variable, but if you begin to cycle through family match and everything else, nothing changes. You have to cycle the gender for everything else to start working and pull you out of the default ped.

**Comment by JosephPentz** [comment]
Personally I would have never thought I’d have to cycle my gender to female back to male to enable the rest of the menu to make it work

**Comment by MissKiddo1987** [comment]
I also noticed with character creation that you can't change how your face looks at the barber shop after you're done with character creation? Not sure if this is already being looked into or not but when making my character today for the test server I couldn't see myself at all till an admin moved me. By this point I could only change my hair, makeup etc etc but not how my face looks.
