### ISSUE TITLE
[BUG] Circuit board in pawn shop menu shows up twice

### ISSUE THREAD

**Issue by robo50111** [ElusionPDX/Ze3o-Reports#46]
**Describe the bug**
Circuit board shows up on the pawn shop selling menu twice

**To Reproduce**
1. Go to the pawn shop
2. Open the menu
3. See circuit board showing up twice

**Expected behavior**
Circuit board showing up only once

**Screenshots**
![image](https://user-images.githubusercontent.com/12085770/118371399-8233c300-b57a-11eb-8a76-cf38b0d892a6.png)

**Comment by ElusionPDX** [comment]
@Digital-Mike
