### ISSUE TITLE
[BUG] Getting jailed will put you inside a building

### ISSUE THREAD

**Issue by Xodius** [ElusionPDX/Ze3o-Reports#48]
**Describe the bug**
Getting jailed will put you inside a building

**To Reproduce**
1. Get sent to jail

**Expected behavior**
Should be in a location that you can still access the rest of the jail yard

**Screenshots**
![image](https://user-images.githubusercontent.com/6254089/118386833-0f086c00-b5cf-11eb-8f67-ed9059b41c3a.png)

**Comment by ElusionPDX** [comment]
When did you try this as jail was redone yesterday and was tested by 4 people

**Comment by Xodius** [comment]
@ElusionPDX This was done right when I filed it. How does one get jailed now?
