### ISSUE TITLE
[BUG] Add Taxi Spawner at the taxi depot. 

### ISSUE THREAD

**Issue by robo50111** [ElusionPDX/Ze3o-Reports#49]
**Describe the bug**
In the old city, you would be able to spawn a taxi at the taxi depot at area code 408

**To Reproduce**
1. Get the taxi job form the job center
2. Go to the taxi depot at area code 408
3. No Taxi spawner

**Expected behavior**
A taxi spawner circle.

**Screenshots**
Expected location of the spawn circle:
![image](https://user-images.githubusercontent.com/12085770/118420917-f01cdf00-b68d-11eb-9cc5-367027464c9f.png)

**Additional context**
Screenshot contains the coords of the expected taxi spawn circle.

**Comment by ElusionPDX** [comment]
Go on duty in the back room will be a blue circle. Then walk out the front
glass doors you will see another blue circle. That is the spawner.

**Comment by ElusionPDX** [comment]
Here is the clock in/out spot
![image](https://user-images.githubusercontent.com/19332765/118503345-8d146200-b6f8-11eb-876b-1610caa79c30.png)

**Comment by ElusionPDX** [comment]
Here is the taxi spawner spot
![image](https://user-images.githubusercontent.com/19332765/118503509-afa67b00-b6f8-11eb-818b-513c70a7c5a7.png)
