### ISSUE TITLE
[ENHANCEMENT] Final Thoughts and Enhancements

### ISSUE THREAD

**Issue by robo50111** [ElusionPDX/Ze3o-Reports#50]
### Taxi Job:
Taxi meter is working, but to get it, you need to get in the back seat of the taxi first and then hop into the drivers seat. If you reset the meter, instead of going down to 0, it goes up to $10.00 and continues to reset to $10.00.

Maybe add a /taxi command to request a taxi if any are available, or link the taxi contact in your phone to a taxi dispatch or something. Right now, the only way to get fares is to advertise on yellow pages. That might be intended so no fault there. The only way to get local calls is to use the Uber app with a taxi cab.

### ATM Robbing:
Have the robbed ATM drop clean money because of how much dirty money it gives you. With the current money washing, you would be doing runs all day to clean that cash and it would take the RP out of the process. Additionally, I would think that ATM money would be clean because its from an ATM. You could even reduce the payout if the ATM's gave clean money.

Another solution would be reducing the amount of dirty money it gives you so that it would be easier to clean.

### Cleaning money:  
The price reduction on the OXY run is good, it is a fair price and you end up making a few hundred dollars with dirty money. However, the amount of dirty money if takes is a little low compared to what it was taking in the old city, I believe it was taking 400-600 dirty money in the old city, greatly speeding up the money washing. 

I have heard that there is something else to speed up money washing in the works, so if this is being looked at, then ignore this section.

**Comment by ElusionPDX** [comment]
The taxi meter starts at 10 bucks.
To open the meter press f10 or f11 i can remember at this time.

Will talk about other stuff later

**Comment by LocoGuero** [comment]
I do agree clean money for an ATM. Just less of it.

**Comment by ElusionPDX** [comment]
The reason we did  dirty is cuz if stuff gives clean then police can take all the money on a person when they get busted doing the crime.  It was more so of a safe guard so people dont get mad at police for taking all there money.

**Comment by LocoGuero** [comment]
Thats a valid point.
