### ISSUE TITLE
[BUG] Cant start SADOT job

### ISSUE THREAD

**Issue by CPatelCLT** [ElusionPDX/Ze3o-Reports#51]
**Describe the bug**
Unable to see the floor blips in the SADOT office to start/stop the job. I have the DOT job already and can manipulate the door locks.

**Expected behavior**
While DOT job is granted, you should see a floor blip to walk into and interact with to start the job. After starting you should see another blip near the back door of the office to spawn the tow truck.

**Screenshots**
https://i.imgur.com/iLLSpJW.jpg (this is an old screenshot but shows the same thing)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - GPU: RTX 3090
 - CPU: 5950X

**Additional context**
This appears to be the same issue we were having before where the job script needed to be restarted or something. It's possible that it's a different issue but it's presenting the same way as before

**Comment by ElusionPDX** [comment]
This will be in today. Need to redo its calling system so it can work with the phone.

**Comment by ElusionPDX** [comment]
See https://github.com/ElusionPDX/ZeroLive/commit/a383eb16f70031d8c0d47a05a18510e026d84eed
