### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Cockpitbuilders** [ElusionPDX/Ze3o-Reports#53]
**Describe the bug**
Going to the barber shop opens 2 menu's on top of each other, and seems like selecting items through the menu doesn;t yield results

**To Reproduce**
1. Go to 'The Barber shop'
2. Click on 'E' in the circle
3. See issue/error <--- Exactly that and I can't find a way to complete the operation (Escape or backspace) No way out of the menu.  Had to noclip to get out.

**Expected behavior**
Two menu's open on top of each other.

**Screenshots**
![image](https://user-images.githubusercontent.com/77129123/118728569-64788f00-b802-11eb-8884-9258dff240d5.png)

**Desktop (please complete the following information):**
 - OS: WIN10
 - GPU: 2070 Super
 - CPU: [8700K]

**Additional context**

**Comment by ElusionPDX** [comment]
That menu was on for MLO edits.
