### ISSUE TITLE
[BUG] Digital Den MLO and Blip is missing / YouTool & Davis Mall Blips missing

### ISSUE THREAD

**Issue by Xodius** [ElusionPDX/Ze3o-Reports#57]
**Describe the bug**

**To Reproduce**
1. Go to Digital Den and look for it on a map
2. Look for YouTool and Davis Mall on the map

**Screenshots**
![image](https://user-images.githubusercontent.com/6254089/118747738-67c64780-b80f-11eb-8ee8-68eea6dda0e1.png)
![image](https://user-images.githubusercontent.com/6254089/118747766-79a7ea80-b80f-11eb-91dd-509d339b19c4.png)
YouTool
![image](https://user-images.githubusercontent.com/6254089/118748114-1a96a580-b810-11eb-82b9-b32935fbb3a7.png)
Davis Mall
![image](https://user-images.githubusercontent.com/6254089/118748207-49ad1700-b810-11eb-884b-55b3fd89e4be.png)

**Comment by ElusionPDX** [comment]
all blips can be found in your F1 menu under the blip part
