### ISSUE TITLE
Pawn shop items incorrectly named ( teddy bear and wallet)

### ISSUE THREAD

**Issue by TLCKAT** [ElusionPDX/Ze3o-Reports#6]
**Describe the bug**
2 items cannot be sold, the spelling is wrong for Wallet, and Trashcan Bear is actually named Dumpster Teddy Bear.

**To Reproduce**

1. Items in list near the bottom, 
2. Wallet is spelled Walet
3. Dumpster Teddy Bear is listed as Trashcan Bear

**Expected behavior**
sellable items, not sellable.

**Screenshots**
![image](https://user-images.githubusercontent.com/84049876/117909047-88d6e780-b2a7-11eb-9a6f-6fe2a5c36fa7.png)

**Desktop (please complete the following information):**
  - OS: Windows 10 Home 64
 - GPU: 8192MB ATI Radeon RX 580 Series 
 - CPU: AMD Ryzen 7 3700X

**Additional context**
N/A

**Comment by ElusionPDX** [comment]
Fixed in commit https://github.com/ElusionPDX/ZeroLive/commit/1af2ff6a5c0b0415f8f0465a3ee64c9e51b52049
