### ISSUE TITLE
[BUG] Pickaxe does not show up in hand after equipping

### ISSUE THREAD

**Issue by KDFRUMDA3** [ElusionPDX/Ze3o-Reports#62]
**Describe the bug**
A clear and concise description of what the bug is. when attempting to use the pickaxe to mine it says it is being equipped but never shows up in my hands
**To Reproduce**
3. See issue/error

**Expected behavior**
A clear and concise description of what you expected to happen. to see pickaxe being physically equipped in hand

**Screenshots**

**Desktop (please complete the following information):**
 - GPU: [e.g. gtx1060]
 - CPU: [e.g. FX8350]

**Additional context**

**Comment by Xodius** [comment]
@KDFRUMDA3 You don't need to equip the pickaxe for mining, you just need to have it on you.

Use the Left-Alt key to inspect and look at the rock. Click your left mouse button and select the context.
