### ISSUE TITLE
[BUG] car is immobile at engine health of 270.02

### ISSUE THREAD

**Issue by KDFRUMDA3** [ElusionPDX/Ze3o-Reports#63]
**Describe the bug**
A clear and concise description of what the bug is. had a few accidents the car should still be working with the engine health at 270.02

**To Reproduce**
3. See issue/error

**Expected behavior**
A clear and concise description of what you expected to happen. expect the vehicle to run until the engine health reaches 0 or near it 

**Screenshots**

**Desktop (please complete the following information):**
 - GPU: [e.g. gtx1060]
 - CPU: [e.g. FX8350]

**Additional context**

**Comment by ElusionPDX** [comment]
From 600 and lower any random thing can happen to the car. From 300 and lower one random engine deaths will be picked.
