### ISSUE TITLE
[BUG] Duplicates found metal detecting

### ISSUE THREAD

**Issue by Xodius** [ElusionPDX/Ze3o-Reports#64]
**Describe the bug**
When metal detecting, you will find two items at every stop

**To Reproduce**
1. Go to beach and use metal detector
2. Locate a ping and dig
3. Notice two of the items dug up

**Expected behavior**
Should be receiving 1 item from each point

**Screenshots**
![image](https://user-images.githubusercontent.com/6254089/118929382-4b063e80-b8f9-11eb-94bd-fb386125e792.png)

**Additional context**

**Comment by Iam74Niner** [comment]
Per D-pad   Issues is still happening are server start

**Comment by Xodius** [comment]
Confirmed that this has been fixed.
