### ISSUE TITLE
[BUG]. Evidence Weight Limit

### ISSUE THREAD

**Issue by ChiefDeputyFlowers** [ElusionPDX/Ze3o-Reports#65]
**Describe the bug**
Is there a way to increase the weight limit for evidence significantly in the event there is more weighted items then anticipated.  Maybe to 300?

**Screenshots**

**Comment by ElusionPDX** [comment]
Thats like 6 times what a player can carry on them.  Are you talking about
slots in the evidence?

**Comment by ChiefDeputyFlowers** [comment]
Before we started the core server, we could not place items off a person, from their car, shell casings from the same related scene in evidence because of the weight limit.   Because there are going to be scenes where there will be 100s of shell casings and other evidence to enter in.  

If there is a way to increase the evidence weight when we enter in evidence it will be helpful.
