### ISSUE TITLE
[BUG] Water in Houses

### ISSUE THREAD

**Issue by Iam74Niner** [ElusionPDX/Ze3o-Reports#66]
Bed room of house is full of water causing you to drown
**To Reproduce**
Walk into house and head towards the bed room

**Expected behavior**not water

**Screenshots**

**Desktop (please complete the following information):**
 - OS: w10
 - GPU: 2070 Supera
 - CPU: 17

**Comment by ElusionPDX** [comment]
Need to know what house you bought. send screen shots of it please.

**Comment by Iam74Niner** [comment]
it was in the houses at 346 closes to the water  while robbing
