### ISSUE TITLE
Can't walk into Digital Den

### ISSUE THREAD

**Issue by NooobVerified** [ElusionPDX/Ze3o-Reports#68]
Was taken to Digital Den to buy a phone and you cant walk past the front door. It opens but its like an invisible wall is there.

**To Reproduce**
1. Go to Digital Den
2. Try to walk through door
3. Door opens but no entry

**Expected behavior**
I thought i was able to walk through the door to buy a phone.

**Screenshots**

**Desktop (please complete the following information):**
 - GPU: [e.g. gtx1060]
 - CPU: [e.g. FX8350]

**Additional context**

**Comment by Xodius** [comment]
This has been fixed.
