### ISSUE TITLE
[BUG] Lockpicks aren't working for vehicles and hotwiring

### ISSUE THREAD

**Issue by Xodius** [ElusionPDX/Ze3o-Reports#7]
**Describe the bug**
Lockpicks aren't working for vehicles and hotwiring

**To Reproduce**
1. Find a locked car
2. While having a lockpick and facing a car - drag the lockpick from your inventory to use
3. See lockpick progression 
4. When trying to enter the vehicle it will still crack out the window and unlock it
5. Using lockpicks while hotwiring yields a negative result as well.

**Expected behavior**
Car is unlocked and hotwire is successful.

Not sure if the system was changed from the previous minigame to perform these actions, but it is  not working in it's current state.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by ElusionPDX** [comment]
Fixed in comment https://github.com/ElusionPDX/ZeroLive/commit/638840dad701bba185351d55c6f6cd9f163081c7
