### ISSUE TITLE
[BUG] Two Progress Bars for Lockpicking

### ISSUE THREAD

**Issue by SuthernSoldier** [ElusionPDX/Ze3o-Reports#72]
**Describe the bug**
You will get two progress bars when lockpicking cars both ignition and doors

**Screenshots**
![20210521104632_1](https://user-images.githubusercontent.com/84158417/119171677-1f32a800-ba22-11eb-8a61-8792924ba8a6.jpg)
![20210521104656_1](https://user-images.githubusercontent.com/84158417/119171685-21950200-ba22-11eb-99f1-0b838298aad6.jpg)

**Comment by ElusionPDX** [comment]
this has been fixed on the dev just not pushed to live yet
