### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by TheClusk** [ElusionPDX/Ze3o-Reports#74]
**Describe the bug**
A clear and concise description of what the bug is: Various menus get stuck on screen and have to F8 out. Has happened at 24/7, Mega mall and now at pawn shop. 

**To Reproduce**
Steps to reproduce the behavior: Not sure how to reproduce, other than to just try different locations and menus?
3. See issue/error

**Expected behavior**
A clear and concise description of what you expected to happen: For the menu to not be stuck and cause me to F8 out of the server.

**Screenshots**

**Desktop (please complete the following information):**
 - GPU: [e.g. gtx1060]
 - CPU: [e.g. FX8350]

**Additional context**

**Comment by CPatelCLT** [comment]
I had this just happen when I accidentally hit F1 while trying to do F2 to open the inventory and the F1 menu got stuck on screen. Had to F8 out of the server

**Comment by Xodius** [comment]
@CPatelCLT @TheClusk Were you both using the "Alt" eye prompt?

**Comment by TheClusk** [comment]
I wasn't. But I think it was due to hitting F1 and F2 like CPatel.

**Comment by ElusionPDX** [comment]
i can add the invy to the f1 menu to fix this issue from being a thing for people
