### ISSUE TITLE
[BUG]oxy run gives no oxy

### ISSUE THREAD

**Issue by Da17ShotKing** [ElusionPDX/Ze3o-Reports#78]
**Describe the bug**
The oxy run gives no oxy and it ttakes 10x as more roll of bill while paying only $125.

**To Reproduce**
3. See issue/error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - GPU: [e.g. gtx1060]
 - CPU: [e.g. FX8350]

**Additional context**

**Comment by ElusionPDX** [comment]
they no longer do for now.
