### ISSUE TITLE
Unable to sell fish found metal detecting on the beach at fish seller[BUG]

### ISSUE THREAD

**Issue by Arget1am** [ElusionPDX/Ze3o-Reports#8]
**Describe the bug**
When attempting to sell fish at the selling location marked on the map, you are prompted that you have no fish to sell, when in fact I have fish to sell.

**To Reproduce**
1. Purchase metal detector
2. Metal detect on beach until you obtain a fish
3. go to La Spada Fish Restaurant to sell fish
4. Attempt to sell fish

**Expected behavior**
Upon verifying that I, in fact, do have fish in my inventory. The expected behaviour is that the nice man will purchase my fish and cook lovely meals with them.

Screenshots:
![fisherror](https://user-images.githubusercontent.com/66976548/117910870-ba9d7d80-b2aa-11eb-93c1-69f61cb77c29.png)
![fisherror1](https://user-images.githubusercontent.com/66976548/117910871-bb361400-b2aa-11eb-801c-f55055b84680.png)

**Desktop (please complete the following information):**
 N/A

**Additional context**
These fish may be intended to sold at a different location., but am unsure.
Interested as to why the metal detector is picking up a fish.

**Comment by ElusionPDX** [comment]
Issue fixed in commit 8e998ca
fixed fishing rod and bait image, fixed wrong item in metal detector fish changed to keyfish
https://github.com/ElusionPDX/ZeroLive/commit/8e998ca0d933d040fd5f85ba567bee64ceb544c2
