### ISSUE TITLE
[BUG] Can only post on twitter once every 10 min 

### ISSUE THREAD

**Issue by MissKiddo1987** [ElusionPDX/Ze3o-Reports#81]
**Describe the bug**
When I post on twitter then go to make another post or reply to someone, I can't. It tells me I can only post 1 every 10 min & to try again. 

**To Reproduce**
3. See issue/error

**Expected behavior**
Should be able to post without waiting 10 min to post again or reply to someone

**Screenshots**

**Desktop (please complete the following information):**
 - GPU: [e.g. gtx1060] 
 - CPU: [e.g. FX8350] 

**Additional context**

**Comment by Xodius** [comment]
This is fixed - You can close it out.
