### ISSUE TITLE
[BUG] Yellow pages on phone 

### ISSUE THREAD

**Issue by MissKiddo1987** [ElusionPDX/Ze3o-Reports#82]
**Describe the bug**
So I'm not sure if this is happening for everyone but when I go to post on yellow pages on my phone, I get a black box & it won't allow me to type anything. I have mouse control on so it should be a little white box & not the big black one that typically shows up when you don't have mouse control on. When mouse control is off it's bringing up the small white box to post instead. I have attached 2 screenshots. One of twitter showing the white box working for mouse control on & the yellow pages with the black box & not the white box that it should be. 
![comparison twitter](https://user-images.githubusercontent.com/84261924/119243176-73c54880-bb32-11eb-8ea2-63c1ff2ade2b.JPG)
![comparison2](https://user-images.githubusercontent.com/84261924/119243177-74f67580-bb32-11eb-9486-b91f76f11b51.JPG)

 

**To Reproduce**
3. See issue/error

**Expected behavior**
Should be able to type with mouse control on in a little white box. 

**Screenshots**

**Desktop (please complete the following information):**
 - GPU: [e.g. gtx1060]
 - CPU: [e.g. FX8350]

**Additional context**

**Comment by Xodius** [comment]
Have you tried a cache clear?

**Comment by MissKiddo1987** [comment]
I honestly didn't even bother checking today after I cleared my cache. I will check tomorrow when I'm back in the city. I know there was a few others who were having the same issue.

**Comment by MissKiddo1987** [comment]
@Xodius Yellow pages is working properly now. Going to close this bug report
