### ISSUE TITLE
[BUG] losing keys after parking in garage

### ISSUE THREAD

**Issue by KDFRUMDA3** [ElusionPDX/Ze3o-Reports#83]
**Describe the bug**
A clear and concise description of what the bug is. purchased a vehicle and had keys up until restart. parked vehicle in garage upon taking it out i did not have keys for it anymor

**To Reproduce**
3. See issue/error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - GPU: [e.g. gtx1060]
 - CPU: [e.g. FX8350]

**Additional context**

**Comment by ElusionPDX** [comment]
when you pull your car out of the garage press M
