### ISSUE TITLE
[BUG] Stuck in Menu

### ISSUE THREAD

**Issue by MikeyOwnz** [ElusionPDX/Ze3o-Reports#85]
**Describe the bug**

sometimes when go to shop i get stuck in the buy menu then i cant click on anything have to leave server then come back

**To Reproduce**
3. See issue/error

**Expected behavior**

**Screenshots**
![20210523143238_1](https://user-images.githubusercontent.com/84683616/119274543-6bc2e280-bbde-11eb-9eeb-edaa71d075f7.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. Win]
 - GPU: [e.g. RTX 2070 Super]
 - CPU: [e.g. Ryzen 7 3700x ]

**Additional context**

**Comment by ElusionPDX** [comment]
see https://github.com/ElusionPDX/Ze3o-Reports/issues/89
