### ISSUE TITLE
[BUG] Local vehicles in SADOT impound lot

### ISSUE THREAD

**Issue by CPatelCLT** [ElusionPDX/Ze3o-Reports#87]
**Describe the bug**
We're getting some local vehicle spawns in the impound lots

**To Reproduce**
Enter and leave the area a few times until you see local vehicles spawn at the lot, sometimes they are there after a server restart

**Expected behavior**
Empty lots other than what SADOT drops in them

**Screenshots**
https://cloud.thehumanpilot.com/s/SGFyW7y8Qf28Msw/preview
https://cloud.thehumanpilot.com/s/wcsMqbQKnneZtgD/preview

**Comment by ElusionPDX** [comment]
https://github.com/ElusionPDX/ZeroLive/commit/23a0456e6db60fc125ce8ce023564af918b1880c
