### ISSUE TITLE
[BUG] Multiple [E] menu's too close, causing inventory lock-up @1001 Gas Station

### ISSUE THREAD

**Issue by TLCKAT** [ElusionPDX/Ze3o-Reports#89]
**Describe the bug**
@ different interactable menu's at the gas station located @1001. One is the gas station menu giving the "Press [E] to Open", then another one right above it "[E]Ron" . Upon pressing E, you get locked with your inventory and store inventory open. can't do anything to get out of it except doing f8 quit.

**To Reproduce**
1. Go to doors of the gas station @1001
2. Press E
3. See that inventory and store inventory opens. You now can no longer do anything to "Esc" the window.

**Expected behavior**
With the placement of the 2 options, there's no "expected behavior", because theoretically... both menu's will try to open at once. But with one of them moved a bit aways from the other, they should work fine

**Screenshots**
Before hitting E
![image](https://user-images.githubusercontent.com/84049876/119377712-6c658280-bc8b-11eb-9574-0bb51fee7dad.png)

After hitting E
![image](https://user-images.githubusercontent.com/84049876/119377818-899a5100-bc8b-11eb-9118-12396caafc32.png)

After cancelling the purchase of the gas station:
![image](https://user-images.githubusercontent.com/84049876/119378048-cb2afc00-bc8b-11eb-9fe4-7192ffe80459.png)

**Desktop (please complete the following information):**
NA

**Additional context**

**Comment by ElusionPDX** [comment]
Should be fixed on next restart
