### ISSUE TITLE
[BUG] Selling Jailbroken Phone

### ISSUE THREAD

**Issue by MisssAmber** [ElusionPDX/Ze3o-Reports#9]
**Describe the bug**
Unable to sell a jailbroken phone in the pawnshop

**To Reproduce**
1. Retrieve a Jailbroken Phone
2. Head to the pawn shop and step in the ring where you can sell items
3. Use the arrow keys to go down until you find "Jailbroken Phone," then try to sell it

**Expected behavior**
Receiving money from the Jailbroken Phone that is being sold

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GPU: gtx1660
 - CPU: AMD Ryzen 7 3700X 8-core processor

**Comment by Xodius** [comment]
@MisssAmber Do you recall where you found the Jailbroken Phone?

**Comment by Xodius** [comment]
@Digital-Mike @ElusionPDX  - Seems the shortname in the pawnshop is listed as "hackerDevice" with a capital D and listed as shortname "hackerdevice" in the main item table.

`itemName = 'hackerDevice', label = 'Jail Broken Phone'`

![image](https://user-images.githubusercontent.com/6254089/118064077-30f3bb80-b34f-11eb-92f9-62b9c55d44f7.png)

**Comment by ElusionPDX** [comment]
https://github.com/ElusionPDX/ZeroLive/commit/14dd0c3ab503c0616425c1bb8d6a531f7e62bc5b
