### ISSUE TITLE
[BUG] radios and communication devices being used underwater

### ISSUE THREAD

**Issue by KDFRUMDA3** [ElusionPDX/Ze3o-Reports#90]
**Describe the bug**
A clear and concise description of what the bug is. radio and talking communication is being used underwater and it clearly should not be.

**To Reproduce**
1. Go to '...' underwater and use radio and or talk and u can be heard clearly.
3. See issue/error

**Expected behavior** radios should be unusable and phones and all voice communications under water

**Screenshots**

**Desktop (please complete the following information):**
 - GPU: [e.g. gtx1060]
 - CPU: [e.g. FX8350]

**Additional context**

**Comment by ElusionPDX** [comment]
This issue should be solved
