### ISSUE TITLE
[BUG] haulage work completely crashes five m

### ISSUE THREAD

**Issue by KDFRUMDA3** [ElusionPDX/Ze3o-Reports#93]
**Describe the bug**
upon selecting a job to do on the haulage work list the character completely freezes and five m becomes unresponsive. have not been able to successfully start a haulage work job.
**To Reproduce**
1. Go to '...' haulage work icon on the map
2. Click on '....'go to the circle on the floor by the door, click on it and select a job to do 
3. See issue/error your character completely freezes and fivem becomes unresponsive

**Expected behavior**
upon selecting a job the truck should appear and you should hook your trailer up to it and start the job.
**Screenshots**

**Desktop (please complete the following information):**
 - GPU: [e.g. gtx1060]
 - CPU: [e.g. FX8350]

**Additional context**

**Comment by ElusionPDX** [comment]
job replaced
