### ISSUE TITLE
[BUG]oxy runs wont exchange money even though rolled notes are in inventory

### ISSUE THREAD

**Issue by KDFRUMDA3** [ElusionPDX/Ze3o-Reports#94]
**Describe the bug**
after about 3 runs the deliveries say no more extra sauce even though there is still rolled notes in inventory

**To Reproduce**
1. Go to '...'oxy run
2. Click on '....'have rolled notes and do runs. after about the third one it stops exchanging notes
3. See issue/error

**Expected behavior**
runs should exchange notes until runs are over or until notes are depleted

**Screenshots**

**Desktop (please complete the following information):**
 - GPU: [e.g. gtx1060]
 - CPU: [e.g. FX8350]

**Additional context**

**Comment by ElusionPDX** [comment]
the amount you need per drop was bumped up to help clean faster $500 per drop
