### ISSUE TITLE
Gates do not open at garage 422

### ISSUE THREAD

**Issue by ChiefDeputyFlowers** [ElusionPDX/Ze3o-Reports#96]
**Describe the bug**
Gates do not open at garage 422, you have to ram them.

**To Reproduce**
1. Go to garage 422
2. Approach the gate
3. Sit forever, then ram it to get in.

**Comment by ElusionPDX** [comment]
fixed, https://github.com/ElusionPDX/ZeroLive/commit/285b7b7166a8fc6e39730cc3485b17925d3c9e3a
