### ISSUE TITLE
[BUG] Taking out cash from the bank or ATM with a full inventory will blackhole the cash

### ISSUE THREAD

**Issue by Xodius** [ElusionPDX/Ze3o-Reports#97]
**Describe the bug**
Taking out cash from the bank with a full inventory will blackhole the cash

**To Reproduce**
1. Fill all inventory item slots
2. go to a bank or ATM and take out money
3. Notice money is not there or in the bank

**Expected behavior**
Transaction should be cancelled and money returned to bank when inventory is full

**Comment by ElusionPDX** [comment]
Nothing can be done about this as you are at your weight limit. So you can not add more items to your player..
