### ISSUE TITLE
[BUG] messages generated behind status bar hud

### ISSUE THREAD

**Issue by KDFRUMDA3** [ElusionPDX/Ze3o-Reports#98]
**Describe the bug**
when recieveing a text message, when getting notified from npcs, or from actions on doors the message is being populate behind the health bar hud and the message is unreadable
**To Reproduce**
1. Go to '...'get a text message or interact with npc, or have to press E or H to interact with a door or other things
3. See issue/error

**Expected behavior**
messages should show up above the hud where it is clearly free from obstruction and clearly visible
**Screenshots**

**Desktop (please complete the following information):**
 - GPU: [e.g. gtx1060]
 - CPU: [e.g. FX8350]

**Additional context**

**Comment by ElusionPDX** [comment]
this should be fixed for the phone
