### ISSUE TITLE
metal detector locks people in place while in car[BUG]

### ISSUE THREAD

**Issue by masterchurro** [ElusionPDX/Ze3o-Reports#99]
**Describe the bug**
i have my metal detector set up as number 5, whenever i press the button by mistake, i can't put the item away, and if i pull it out by mistake in the car, you can get out off the car at all, i have to re log
**To Reproduce**
3. See issue/error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - GPU: [e.g. gtx1060]
 - CPU: [e.g. FX8350]

**Additional context**

**Comment by ElusionPDX** [comment]
This is done on purpose. To stop people from fast sweepong the beach in a car
